export const dom = {
  body: document.querySelector("body"),
  content: document.querySelector("main"),
  logo: document.querySelector("h1"),
  burger: document.querySelector("#burger__menu"),
  menu: document.querySelector("#menu__wrapper"),
  mode: document.querySelector(".mode__wrapper"),
  startBtn: document.querySelector(".start__btn"),
  repeatBtn: document.querySelector(".repeat__btn"),
  modeBtn: document.querySelector(".mode"),
  statsBtn: document.querySelector(".stats"),
  menuList: document.querySelector("ul"),
  cardWrapper: document.querySelector(".card__wrapper"),
  answerWrapper: document.querySelector(".answer__wrapper"),
  statsWrapper: document.querySelector(".stats__wrapper"),
  statsBtnsWrapper: document.querySelector(".stats__btns"),
  resetBtn: document.querySelector(".reset"),
  repeatWordsBtn: document.querySelector(".repeat__words"),
  tableHead: document.querySelector("thead"),
  tableBody: document.querySelector("tbody"),
};
